### PR TITLE
added View Point functionality

### LINKED ISSUE #267: View Point crashes app
Screenshot 2019-08-30 13 54 30
this is on mino

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Added view point functionality, using the old bridge UI as a reference. Not sure if you guys have designs for this but happy to modify to accomodate. Fixes #267 

Screen Shot 2019-08-31 at 1 12 52 pm

### CODE REVIEW

**Comment by Fang-** [comment]
Nice! Not entirely sure we want this in for new Bridge though, since it doesn't really let you see or do anything for points you don't own. I think a more proper "view point" page might be part of network explorer work, but unsure.

**Comment by Fang-** [comment]
ping @vvisigoth

**Comment by Fang-** [comment]
ping @vvisigoth again, are we dropping this PR in favor of the network explorer, or do we want it in for now?

**Comment by Fang-** [comment]
ping @vvisigoth third time! I guess I'll just close this if no response by end of week. (thanks anyway, @liam-fitzgerald!)

**Comment by vvisigoth** [comment]
Sadly will close until we figure out the network explorer designs.

**Pull request closed without merging**
