### PR TITLE
deps: upgrade to WalletConnect  1.7.5

### PR DESCRIPTION
**Pull request by tomholford**
This upgrades the WalletConnect dependencies to 1.7.5 (from 1.7.1). This change is motivated by #1006. 

TODO:

- [ ] test with Gnosis Safe

### CODE REVIEW

**Comment by tomholford** [comment]
@tacryt-socryp Since I don't have access to a Gnosis Safe, wondering if you could help me test this when you have a moment.

Please check out this branch and run with `npm run pilot-mainnet` and see if you have any luck.

**Comment by tacryt-socryp** [comment]
could you publish it to a bridge subdomain @nerveharp ?

**Comment by nerveharp** [comment]
Let me ask @yosoyubik and @Fang-; it's nearly midnight their time so it may be ready for you tomorrow.

I expect SSL is mandatory?

**Comment by yosoyubik** [comment]
Deployed this to https://bridge-staging.urbit.org/

**Comment by nerveharp** [comment]
@tomholford How is testing going with this?

**Comment by tomholford** [comment]
Closed in favor of #1057 , WC was upgraded to 1.8.0

**Pull request closed without merging**
