### PR TITLE
Metamask authentication

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Adds Metamask authentication to log into bridge.

Metamask doesn't support signing a tx before broadcast, so we "sign" a fake tx
and have metamask sign it upon broadcasting.

### CODE REVIEW

**Comment by vvisigoth** [comment]
I'll confirm functionality, @Fang- @shrugs would you mind looking at style when you get a chance?

**Comment by jyng** [comment]
I think we want to move towards a master-ticket focussed login and deemphasize other login methods. It gives more focus to a suggested path and makes the login page feel less crowded. Let's move forward with this.
login other
login other expanded

**Comment by jyng** [comment]
@liam-fitzgerald Do you think this is doable?

**Comment by liam-fitzgerald** [comment]
Absolutely will update

**Comment by galenwp** [comment]
@jyng I could see us also putting master ticket shards under 'other'

**Comment by vvisigoth** [comment]
Looks good, @liam-fitzgerald just pulled and ran with @jyng

**Comment by Fang-** [comment]
Better late than never: this PR seems fine code-wise! Feels a bit weird to be doing the fake transaction thing, trying to think of cases where it could bite us but coming up blank. Probably Fine™.

> It gives more focus to a suggested path and makes the login page feel less crowded. Let's move forward with this.
> login other

That looks kinda Bad though. I think we passed the point where we need to go back to a dropdown or similar for this, @jyng?

**Pull request merged**
