### PR TITLE
Loading screen on points view

### PR DESCRIPTION
**Pull request by liam-fitzgerald**
Shows a loading indicator when chain state is loading, so that
Urbit HD wallets immediately show the (only) point view instead
of flashing through the point select view.

### CODE REVIEW

**Comment by vvisigoth** [comment]
This still causes a flash of family view on loading an address with one point.

Kapture 2019-10-30 at 14 10 09

**Comment by liam-fitzgerald** [comment]
fixed

**Comment by vvisigoth** [comment]
Now the opposite. Eternal loading on single point ownership.

Kapture 2019-10-31 at 17 31 56

**Comment by vvisigoth** [comment]
Still hanging.

To be clear, I'm testing by booting with clean chain state. Creating a ~zod, logging out and then logging back in.

**Comment by vvisigoth** [comment]
Any progress on this one?

**Pull request merged**
