### PR TITLE
Ga Patch 1

### PR DESCRIPTION
**Pull request by gavinpatkinson**
This PR addresses the following issues:

- [ ] refactor unlock/node selection forms for consistency
- [x] #7
- [x] #6
- [x] visual sigil bugs
- [x] visual layout bugs

### CODE REVIEW

**Comment by gavinpatkinson** [comment]
Thanks for the review. Gonna release this EOW.

**Comment by gavinpatkinson** [comment]
@jtobin can you elaborate on "Ticket and shard auth don't seem to set the wallet prop accurately; possibly something to do with async mumbojumbo?"

**Comment by jtobin** [comment]
@gavinpatkinson When trying to authenticate via master ticket or shards, I observed that I'd get forwarded to the points view without a wallet prop actually being set.

I took a brief look at this and guessed that it might be due to React's asynchronous updating in some combination of `walletFromTicket` and `handleSubmit`, but that was just my initial suspicion.  I.e., perhaps we need to better enforce that `setWallet` do its thing before `popRoute` / `pushRoute`, or something.

I messed around with it for a few minutes but didn't get anywhere with it.  I can definitely take another look when I get a chance.

**Comment by Fang-** [comment]
Pinging on this. I think #7 was also fixed in @c-johnson's recent router work, so there may be more conflicts here than just moved/renamed files.

**Comment by gavinpatkinson** [comment]
Closing because this is now very out of date.

**Comment by jtobin** [comment]
@Fang- I've ripped out the optional passphrase stuff and PR'd it in #94.

**Pull request closed without merging**
