### PR TITLE
The site displays correctly on mobile

### PR DESCRIPTION
**Pull request by willbach**

### CODE REVIEW

**Comment by tomholford** [comment]
LGTM. From a product perspective, do we still consider mobile-support a security risk? If not, perhaps we should remove this (in `ActivateCodeForm`):

```tsx
  const activationAllowed = useBreakpoints([false, true, true]);

    // ....

  {!activationAllowed && (
    <Grid.Item full as={WarningBox} className="mt4">
      For your security, please access Bridge on a desktop device.
    </Grid.Item>
  )}
```

**Review by tomholford — APPROVED** [review]
LGTM

**Comment by willbach** [comment]
> LGTM. From a product perspective, do we still consider mobile-support a security risk? If not, perhaps we should remove this (in `ActivateCodeForm`):
> 
> ```tsx
>   const activationAllowed = useBreakpoints([false, true, true]);
> 
>     // ....
> 
>   {!activationAllowed && (
>     <Grid.Item full as={WarningBox} className="mt4">
>       For your security, please access Bridge on a desktop device.
>     </Grid.Item>
>   )}
> ```

I'm not sure, @nerveharp @Fang- do you know if mobile is still a security risk?

**Comment by nerveharp** [comment]
I think leaving the warning in is fine. If you want to do this from your phone, you're taking on that risk and all that implies.

**Pull request merged**
