### PR TITLE
add old PCR fonts

### PR DESCRIPTION
**Pull request by g-a-v-i-n**
- add work sans
- add SF Pro

### CODE REVIEW

**Comment by g-a-v-i-n** [comment]
I have resolved the build issues in PCR and updated the fonts to the new fonts, this is no longer needed.

**Comment by Fang-** [comment]
Ah, what timing. Was about to tell you the following, but I think that's obsolete then.

image

In both Firefox and Chrome. I cleared out the `node_modules` and did a fresh `npm install` beforehand.

**Comment by matildepark** [comment]
Times New Roman! It's so classy now!

**Comment by alexmatz** [comment]
this PR is dead. @Fang- can you update paper collateral renderer on Bridge and see if that fixes the font issue on 1.1.2?

**Comment by Fang-** [comment]
Continuing comms over email now for slightly less overhead. For the public record: fonts still broken in 1.1.2.

**Pull request closed without merging**
