### PR TITLE
Use latest Trezor Connect

### PR DESCRIPTION
**Pull request by Fang-**
This makes it compatible with latest Trezor firmware.

Also took the liberty of re-enabling Trezor support in offline mode.

### CODE REVIEW

**Comment by jtobin** [comment]
Looks good -- only comment is that IIRC we removed the Trezor auth from offline mode for a specific reason (initially we had enabled it, because yes, you can still use the thing while in offline mode).  But I actually can't find anything in issues/PRs for why we would have removed it exactly.

@iamwillkim do you remember what was up with that?

**Comment by alexmatz** [comment]
hey @iamwillkim, any idea why you guys removed Trezor support in offline mode?

**Comment by iamwillkim** [comment]
@fang I think we decided to do this because trezor required a server-side connection for auth. If the new trezor connection works offline though, keep it in!

**Comment by Fang-** [comment]
It doesn't work in "my machine has no internet" offline mode, but it works fine in "I want to do weird things/testing so I selected" offline mode.

If the user tries to use Trezor in "my machine has no internet" mode, then it will fail at the very next step, and be obvious about the fact that it's a Trezor-side limitation. (To be honest, using a hardware wallet with an airgapped machine feels a bit too paranoid, but hey.)

**Comment by alexmatz** [comment]
I don't have strong feelings about this, but @Fang-,  is seems like an edge case that could cause less than expert level users frustration?

**Comment by Fang-** [comment]
It's an edge case I don't imagine less than experienced users ending up in:
1. Having a hardware wallet, and
2. User an airgapped (or otherwise disconnected) machine.

**Pull request merged**
